N_ITEMS_MAX = 960


PROJECT_ID = "recove-450509"
DATASET_ID = "vinted"

CATALOG_TABLE_ID = "catalog"
CATALOG_IMPORTANCE_TABLE_ID = "catalog_importance"
ITEM_TABLE_ID = "item"
IMAGE_TABLE_ID = "image"
CATEGORY_TABLE_ID = "category"
LIKES_TABLE_ID = "likes"
ITEM_DETAILS_TABLE_ID = "item_details"

STAGING_ITEM_TABLE_ID = "item_staging"
STAGING_IMAGE_TABLE_ID = "image_staging"

VALID_CATALOG_CODES = ["WOMEN_ROOT", "MENS", "DESIGNER_ROOT"]

CATALOG_FIELDS = ["id", "title", "code", "url", "women"]
VALID_FILTER_KEYS = ["brand", "color", "material", "patterns"]

DESIGNER_CATALOG_IDS = [2984, 2985, 2986, 2987, 2990, 2991, 2992]
VINTAGE_BRAND_ID = 14803

MAX_BRAND_TITLE_LENGTH = 35


POPULAR_BRANDS = [
    "adidas",
    "Nike",
    "Ralph Lauren",
    "Carhartt",
    "GUESS",
    "Camaïeu",
    "Cache Cache",
    "Asics",
    "Vera Pelle",
    "Tommy Hilfiger",
    "Levi's",
    "Longchamp",
    "Esprit",
    "Amisu",
    "Uniqlo",
    "Puma",
    "Diesel",
    "Subdued",
    "Stüssy",
    "Lacoste",
    "Dr. Martens",
    "Weekday",
    "Massimo Dutti",
    "Terranova",
    "Abercrombie & Fitch",
    "New Balance",
    "Etam",
    "Miu Miu",
    "Gémo",
    "Timberland",
    "Coach",
    "Converse",
    "UGG",
    "Naf Naf",
    "Noir",
    "Dazy",
    "Gucci",
    "Stivali",
    "Burberry",
    "Celio",
    "Prada",
    "New Era",
    "New Collection",
    "Brandy Melville",
    "Onitsuka Tiger",
    "Morgan",
    "Calvin Klein",
    "COS",
    "H&M Divided",
    "Springfield",
    "OVS",
    "Vivienne Westwood",
    "Zadig & Voltaire",
    "Tezenis",
    "GAP",
    "CHROME",
    "NO LABEL",
    "The North Face",
    "Birkenstock",
    "Desigual",
    "Jack & Jones",
    "United Colors of Benetton",
    "Loavies",
    "Sfera",
    "Bonobo",
    "adidas Originals",
    "Vintage Chic",
    "Amazon",
    "Quartz",
    "Piazza Italia",
    "Jules",
    "onbekend",
    "Fashion",
    "Gazelle",
    "Donna",
    "Golden Goose",
    "Denim",
    "Sézane",
    "The Genuine Leather",
    "Corteiz",
    "My Jewellery",
    "Atmosphere",
    "Mai",
    "True Religion",
    "Tamaris",
    "JNCO",
    "MNG",
    "Mano",
    "Dickies",
    "Clockhouse",
    "Isabel Marant",
    "Gerard Darel",
    "s.Oliver",
    "Jordan",
    "Calliope",
    "Uomo",
    "Reserved",
    "Polo Ralph Lauren",
    "Romwe",
    "Giacca",
    "Salomon",
    "Zuiki",
    "Graceland",
    "Dior",
    "& Other Stories",
    "Mim",
    "Costes",
    "River Island",
    "Liu Jo",
    "Benetton",
    "In Extenso",
    "La Redoute",
    "Gina Tricot",
    "Boots",
    "Dolce & Gabbana",
    "motivi",
    "Michael Kors",
    "Vila",
    "Set",
    "El Corte Inglés",
    "Alcott",
    "TEX",
    "Even&Odd",
    "Decathlon",
    "Bizzbee",
    "Unique",
    "Louis Vuitton",
    "ORSAY",
    "Yves Saint Laurent",
    "Vans",
    "Pepe Jeans",
    "Sandro",
    "Don't Call Me Jennyfer",
    "Concept",
    "Trendyol",
    "Lancaster",
    "Juicy Couture",
    "Maje",
    "Creeks",
    "Tom Tailor",
    "Sisley",
    "Superdry",
    "ELEGANTE",
    "PrimaDonna",
    "Supreme",
    "Chloé",
    "U.S. Polo Assn.",
    "KOOKAÏ",
    "Pieces",
    "Divided",
    "Beige",
    "BDG",
    "Stone Island",
    "CASIO",
    "Tiffosi",
    "American Vintage",
    "Devred",
    "JDY",
    "Dunnes Stores",
    "Street One",
    "Under Armour",
    "Ed Hardy",
    "Tissaia",
    "Scuffers",
    "Yessica",
]
