name: Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'

jobs:
  fetch-combinations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - women: "true"
            only_vintage: "false"
          - women: "true"
            only_vintage: "true"
          - women: "false"
            only_vintage: "false"
          - women: "false"
            only_vintage: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Display Matrix Combination
        run: |
          echo "Running with configuration:"
          echo "WOMEN: ${{ matrix.women }}"
          echo "ONLY_VINTAGE: ${{ matrix.only_vintage }}"

      - name: Build Docker Image
        run: docker build -t fetch .

      - name: Run Docker Container
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
        run: docker run -e SECRETS_JSON fetch --women ${{ matrix.women }} --only_vintage ${{ matrix.only_vintage }} --filter_by None